/** Navigation targets for Command Palette actions handled outside ChatbotPage modals */
export const CHAT_COMMAND_NAV_ROUTES: Record<string, string> = {
  analytics: "/analytics",
  vault: "/vault",
  "gemini-analytics": "/settings?section=models",
  "custom-instructions": "/settings?section=personalization",
  google: "/profile?tab=linked",
  "script-automation": "/workspace",
  "agent-workflows": "/workspace",
  "fine-tuning": "/workspace",
  "white-label": "/workspace",
  creative: "/studio",
  document: "/forge?mode=documents",
  sovereign: "/sovereign-data",
  security: "/security-audit",
  "knowledge-vault": "/knowledge",
  memory: "/shadow-memory",
  code: "/ide",
  planner: "/workspace",
  organize: "/workspace",
  eco: "/transparency",
  "multi-model": "/settings?section=models",
  agentic: "/missioncontrol",
  camera: "/chatbot",
  vision: "/chatbot",
  branching: "/chatbot",
  "image-decoder": "/chatbot",
  "cognitive-loop": "/missioncontrol",
  "canvas-document": "/ide",
  wordle: "/chatbot",
};

export const CHAT_COMMAND_MODAL_ACTIONS = new Set([
  "new-chat",
  "deep-research",
  "image",
  "voice",
  "browser",
  "missions",
  "offline-tools",
]);
