/** Navigation targets for Command Palette actions handled outside ChatbotPage modals */
export const CHAT_COMMAND_NAV_ROUTES: Record<string, string> = {
  analytics: "/insights?tab=usage",
  vault: "/security?tab=vault",
  "gemini-analytics": "/settings?section=models",
  "custom-instructions": "/settings?section=personalization",
  google: "/profile?tab=linked",
  "script-automation": "/workspace?tab=automate",
  "agent-workflows": "/workspace?tab=agents",
  "fine-tuning": "/personal-llm",
  "white-label": "/enterprise",
  document: "/forge?mode=documents",
  sovereign: "/sovereign-data",
  security: "/security?tab=audit",
  "knowledge-vault": "/research?tab=knowledge",
  code: "/ide",
  organize: "/workspace",
  eco: "/transparency",
  agentic: "/execute",
  branching: "/chatbot",
  "canvas-document": "/ide",
  referral: "/referral",
  workspace: "/workspace",
  "code-ide": "/ide",
  marketplace: "/marketplace",
  "privacy-score": "/security?tab=score",
};

/** Open in-chat modals instead of navigating away */
export const CHAT_COMMAND_MODAL_ACTIONS = new Set([
  "new-chat",
  "deep-research",
  "image",
  "voice",
  "browser",
  "missions",
  "offline-tools",
  "offline",
  "multi-model",
  "creative",
  "vision",
  "camera",
  "planner",
  "image-decoder",
  "cognitive-loop",
  "memory-panel",
  "intelligence-hub",
  "knowledge-vault-modal",
  "wordle",
  "bunker",
]);
