/** Navigation targets for Command Palette actions handled outside ChatbotPage modals */
export const CHAT_COMMAND_NAV_ROUTES: Record<string, string> = {
  vault: "/security?tab=vault",
  "custom-instructions": "/settings?section=personalization",
  "script-automation": "/workspace?tab=automate",
  "fine-tuning": "/personal-llm",
  "white-label": "/enterprise",
  document: "/forge?mode=documents",
  sovereign: "/sovereign-data",
  security: "/security?tab=audit",
  code: "/ide",
  computer: "/computer",
  "canvas-document": "/ide",
  referral: "/referral",
  workspace: "/workspace",
  "code-ide": "/ide",
  marketplace: "/marketplace",
  "privacy-score": "/security?tab=score",
  theme: "/templates?tab=custom",
  templates: "/templates",
  missions: "/missioncontrol",
};

/** Open in-chat modals instead of navigating away */
export const CHAT_COMMAND_MODAL_ACTIONS = new Set([
  "new-chat",
  "deep-research",
  "image",
  "music",
  "google",
  "voice",
  "browser",
  "offline-tools",
  "offline",
  "multi-model",
  "creative",
  "vision",
  "camera",
  "planner",
  "image-decoder",
  "cognitive-loop",
  "memory-panel",
  "intelligence-hub",
  "knowledge-vault-modal",
  "knowledge-vault",
  "wordle",
  "bunker",
  "branching",
  "eco",
  "screen-agent",
  "vision-agent",
  "agentic",
  "agent-workflows",
  "analytics",
  "gemini-analytics",
  "organize",
  "uncensored-arena",
  "shadow-cowork",
]);
