import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export async function exportChatToPdf(
  messages: { role: string; content: string; timestamp?: string | Date }[],
  title: string = "ShadowTalk AI - Chat Log",
) {
  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const PAGE_WIDTH = 210;
  const PAGE_HEIGHT = 297;
  const MARGIN = 16;
  const FOOTER_Y = PAGE_HEIGHT - 10;
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // Top Accent Banner
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, PAGE_WIDTH, 26, "F");

  doc.setFillColor(6, 182, 212); // Cyan accent bar
  doc.rect(0, 26, PAGE_WIDTH, 1.5, "F");

  // Header Title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(248, 250, 252);
  doc.text("SHADOWTALK AI", MARGIN, 13);

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text("Autonomous Conversation Transcript • Verified Audit Log", MARGIN, 19);

  // Metadata block
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text(title, MARGIN, 36);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(`Exported: ${dateStr} • Total Messages: ${messages.length}`, MARGIN, 41);

  // Table Data
  const tableData = messages.map((m) => {
    const isUser = m.role === "user";
    const sender = isUser ? "YOU" : "SHADOWTALK";
    let timeStr = "";
    if (m.timestamp) {
      try {
        const d = m.timestamp instanceof Date ? m.timestamp : new Date(m.timestamp);
        timeStr = d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
      } catch {
        // ignore
      }
    }
    const senderCell = timeStr ? `${sender}\n${timeStr}` : sender;
    return [senderCell, m.content];
  });

  autoTable(doc, {
    startY: 46,
    head: [["Participant", "Message Content"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    columnStyles: {
      0: { cellWidth: 32, fontStyle: "bold", fontSize: 8, textColor: [30, 41, 59] },
      1: { cellWidth: 146, fontSize: 8.5, textColor: [51, 65, 85] },
    },
    styles: {
      cellPadding: 3.5,
      lineColor: [226, 232, 240],
      lineWidth: 0.15,
      overflow: "linebreak",
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: MARGIN, right: MARGIN },
  });

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184);
    doc.setDrawColor(226, 232, 240);
    doc.line(MARGIN, FOOTER_Y - 3, PAGE_WIDTH - MARGIN, FOOTER_Y - 3);
    doc.text("Generated by ShadowTalk AI Intelligence", MARGIN, FOOTER_Y);
    doc.text(`Page ${p} of ${pageCount}`, PAGE_WIDTH / 2, FOOTER_Y, { align: "center" });
    doc.text("Confidential Log", PAGE_WIDTH - MARGIN, FOOTER_Y, { align: "right" });
  }

  doc.save(`ShadowTalk_${title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf`);
}
