import { useState, useEffect, useRef } from "react";
import { ImageIcon, Loader2, Download, X, RefreshCw, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { generateCloudImage } from "@/lib/cloudImage";

interface ImageGeneratorProps {
  onClose: () => void;
  onImageGenerated: (imageUrl: string, prompt: string) => void;
  initialPrompt?: string;
  autoGenerate?: boolean;
}

const STYLE_PRESETS = [
  { id: "photoreal", label: "Photoreal", suffix: "ultra photorealistic, shot on a full-frame camera with an 85mm f/1.4 lens, natural light, razor-sharp focus, fine skin and material texture, true-to-life color, subtle depth of field" },
  { id: "cinematic", label: "Cinematic", suffix: "cinematic still, anamorphic lens, dramatic volumetric lighting, rich film grain, deep shadows and controlled highlights,色 graded like a feature film" },
  { id: "illustration", label: "Illustration", suffix: "masterful digital illustration, confident linework, layered painterly shading, harmonious palette, expressive composition" },
  { id: "product", label: "Product", suffix: "high-end studio product photography, seamless gradient backdrop, softbox lighting with crisp specular highlights, immaculate reflections, catalog-ready" },
  { id: "art", label: "Fine art", suffix: "gallery-grade fine art rendering, exquisite detail, balanced composition, museum lighting, timeless mood" },
] as const;

const QUALITY_SUFFIX =
  "extremely high detail, flawless anatomy and geometry, no artifacts, no watermark, no text, professional composition, ultra-high resolution";

export const ImageGenerator = ({ onClose, onImageGenerated, initialPrompt, autoGenerate }: ImageGeneratorProps) => {
  const [prompt, setPrompt] = useState(initialPrompt || "");
  const [style, setStyle] = useState<string>("photoreal");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isFinal, setIsFinal] = useState(false);
  const { toast } = useToast();
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => {
    if (autoGenerate && initialPrompt && !isGenerating && !generatedImage && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      setTimeout(() => handleGenerate(), 100);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, initialPrompt, hasAutoGenerated]);

  useEffect(() => () => abortRef.current?.abort(), []);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setGeneratedImage(null);
    setIsFinal(false);

    const preset = STYLE_PRESETS.find((s) => s.id === style) ?? STYLE_PRESETS[0];
    const fullPrompt = `${prompt.trim()}. ${preset.suffix}. ${QUALITY_SUFFIX}`;

    const controller = new AbortController();
    abortRef.current = controller;

    try {
      const finalUrl = await generateCloudImage(fullPrompt, {
        signal: controller.signal,
        onFrame: (dataUrl, final) => {
          setGeneratedImage(dataUrl);
          setIsFinal(final);
        },
      });
      setGeneratedImage(finalUrl);
      setIsFinal(true);
      onImageGenerated(finalUrl, prompt);
      toast({ title: "Image generated!" });
    } catch (error) {
      if (controller.signal.aborted) return;
      console.error("Image generation error:", error);
      setGeneratedImage(null);
      toast({
        title: "Generation failed",
        description: error instanceof Error ? error.message : "Could not generate image. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = () => {
    if (!generatedImage) return;
    const link = document.createElement("a");
    link.href = generatedImage;
    link.download = `shadowtalk-${Date.now()}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-card border border-border rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border shrink-0">
          <div className="flex items-center gap-2">
            <ImageIcon className="h-5 w-5 text-primary" />
            <span className="font-medium">Shadow Studio — Image Generation</span>
            <span className="text-xs text-muted-foreground">(Ultra quality)</span>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Content */}
        <div className="p-4 space-y-4 overflow-y-auto flex-1">
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Describe your image</label>
            <Input
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="A futuristic cityscape at sunset with flying cars..."
              disabled={isGenerating}
              onKeyPress={(e) => e.key === "Enter" && handleGenerate()}
            />
            <p className="text-xs text-muted-foreground">
              Be descriptive! Include subject, style, mood, colors, lighting and composition.
            </p>
          </div>

          {/* Style presets */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground">Look</label>
            <div className="flex flex-wrap gap-2">
              {STYLE_PRESETS.map((s) => (
                <Button
                  key={s.id}
                  size="sm"
                  variant={style === s.id ? "default" : "outline"}
                  onClick={() => setStyle(s.id)}
                  disabled={isGenerating}
                >
                  {s.id === style && <Sparkles className="h-3 w-3 mr-1" />}
                  {s.label}
                </Button>
              ))}
            </div>
          </div>

          {/* Loading State (before the first preview frame) */}
          {isGenerating && !generatedImage && (
            <div className="flex items-center justify-center py-16 bg-muted/30 rounded-lg border border-dashed border-border">
              <div className="text-center space-y-3">
                <Loader2 className="h-10 w-10 animate-spin mx-auto text-primary" />
                <p className="text-sm text-muted-foreground">Painting your image…</p>
                <p className="text-xs text-muted-foreground">Previews appear as it renders</p>
              </div>
            </div>
          )}

          {/* Generated / streaming Image */}
          {generatedImage && (
            <div className="space-y-3">
              <div className="relative rounded-lg overflow-hidden border border-border bg-muted/20">
                <img
                  src={generatedImage}
                  alt={prompt}
                  className={`w-full h-auto max-h-[400px] object-contain transition-all duration-500 ${
                    isFinal ? "blur-0" : "blur-xl scale-105"
                  }`}
                />
                {isFinal && (
                  <div className="absolute top-2 right-2 flex gap-2">
                    <Button
                      size="sm"
                      variant="secondary"
                      onClick={handleDownload}
                      className="bg-background/80 backdrop-blur-sm"
                    >
                      <Download className="h-4 w-4 mr-1" />
                      Download
                    </Button>
                  </div>
                )}
                {!isFinal && (
                  <div className="absolute bottom-2 left-2 text-xs px-2 py-1 rounded bg-background/80 backdrop-blur-sm text-muted-foreground">
                    Rendering…
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Actions */}
          <div className="flex justify-end gap-2 pt-2">
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
            {generatedImage && isFinal && (
              <Button
                variant="outline"
                onClick={() => {
                  setGeneratedImage(null);
                  setIsFinal(false);
                }}
              >
                <RefreshCw className="h-4 w-4 mr-2" />
                New Image
              </Button>
            )}
            <Button onClick={handleGenerate} disabled={!prompt.trim() || isGenerating} className="btn-glow">
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <ImageIcon className="h-4 w-4 mr-2" />
                  Generate
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};
