// This file is auto-generated by Lovable. Do not modify it.
// Robust version: use real Lovable auth when installed; fallback to safe no-op shapes when not.

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

let lovableAuthCached: { signInWithOAuth: (provider: string, opts?: SignInOptions) => Promise<{ error?: Error; redirected?: boolean }> } | null = null;

async function getLovableAuth() {
  if (lovableAuthCached) return lovableAuthCached;

  try {
    const mod = await import("@lovable.dev/cloud-auth-js");
    const create = (mod as any).createLovableAuth?.bind(mod) || (mod as any).default?.createLovableAuth?.bind(mod);
    if (typeof create === "function") {
      lovableAuthCached = create({});
      return lovableAuthCached;
    }
  } catch (e) {
    console.warn("[lovable] runtime unavailable:", e);
  }

  return {
    signInWithOAuth: async (_provider: string, _opts?: SignInOptions) => {
      return { error: new Error("Lovable auth is not configured.") };
    },
  };
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: string, opts?: SignInOptions) => {
      const auth = await getLovableAuth();
      try {
        return await auth.signInWithOAuth(provider, opts);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error("Lovable auth runtime failed.") };
      }
    },
  },
};
