// This file is auto-generated by Lovable. Do not modify it.
// Safe fallback: if Lovable auth runtime is absent, all auth methods return a normal result object.

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

function createSafeLovableAuth() {
  return {
    signInWithOAuth: async (_provider: "google" | "apple" | "microsoft" | "lovable", _opts?: SignInOptions) => {
      return { error: new Error("Lovable auth is not installed.") };
    },
  };
}

export const lovable = {
  auth: createSafeLovableAuth(),
};
