// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

const isLocalFirst = import.meta.env.VITE_LOCAL_FIRST === "true";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export type LovableAuthHandle = {
  signInWithOAuth: (
    provider: "google" | "apple",
    opts?: SignInOptions
  ) => Promise<{
    redirected?: boolean;
    tokens?: {
      access_token: string;
      refresh_token: string;
      expires_in: number;
    };
    error?: Error;
  }>;
};

async function createLovableAuthSafe(): Promise<LovableAuthHandle | null> {
  if (isLocalFirst) {
    console.warn("[lovable] Local-first mode is active. Lovable Cloud auth is disabled.");
    return null;
  }

  console.warn(
    "[lovable] Cloud auth package is not installed in this build. Use local-first mode or restore `@lovable.dev/cloud-auth-js`."
  );
  return null;
}

let lovableAuth: LovableAuthHandle | null = null;

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple",
      opts?: SignInOptions
    ) => {
      if (isLocalFirst) {
        console.warn("[lovable] signInWithOAuth is not available in local-first mode.");
        return { error: new Error("Lovable auth is disabled in local-first mode.") };
      }

      lovableAuth ||= (await createLovableAuthSafe()) ?? null;
      if (!lovableAuth) {
        return { error: new Error("Lovable auth is unavailable because cloud-auth-js is not installed.") };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
