// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/answer-faq.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var PRODUCT = {
  name: "ShadowTalk AI",
  tagline: "A sovereign agentic AI workspace: encrypted chat, Mission Control missions, 30+ tools, voice, code IDE, desktop app, and optional on-device models.",
  website: "https://www.shadowtalk-ai.com",
  founder: "Zain Ahmed Fahad Patel (Karachi, Pakistan)",
  freeTier: "Free tier with no credit card: 5,000 chat messages, 20 image generations, 20 document generations, 5 deep-research tasks.",
  privacy: "Privacy-first: client-side encryption for the Stealth Vault, local-first storage, optional offline models so normal chat can run fully on-device."
};
var PLANS = [
  {
    name: "Free",
    price: "$0",
    highlights: [
      "5,000 chat messages",
      "20 image + 20 document generations",
      "5 deep-research tasks",
      "No credit card required"
    ]
  },
  {
    name: "Pro",
    price: "$5/month",
    highlights: ["Higher limits", "Priority routing", "Full tool suite"]
  },
  {
    name: "Premium",
    price: "$15/month",
    highlights: ["Mission Control automation", "Advanced research", "Creative Studio"]
  },
  {
    name: "Elite",
    price: "$20/month",
    highlights: ["Maximum limits", "Enterprise features", "Priority support"]
  }
];
var FEATURES = [
  {
    name: "Agentic Chat",
    category: "chat",
    route: "/chatbot",
    description: "Multi-model agentic chat with tool orchestration, documents, images, voice input and code execution."
  },
  {
    name: "Mission Control",
    category: "automation",
    route: "/execute",
    description: "Long-running autonomous missions with real web search, scraping and step-by-step execution logs."
  },
  {
    name: "Deep Research",
    category: "research",
    route: "/deep-research",
    description: "Multi-step research with citations and selectable depth."
  },
  {
    name: "Strategy Agent",
    category: "business",
    route: "/strategy-agent",
    description: "CEO-suite business strategy, 12-month simulations and hype/trend scouting."
  },
  {
    name: "Personal IDE",
    category: "code",
    route: "/ide",
    description: "Monaco-based editor with AI code generation and an in-browser execution sandbox."
  },
  {
    name: "Creative Studio",
    category: "media",
    route: "/studio",
    description: "AI media and document editor: images, audio, video and presentation building."
  },
  {
    name: "Stealth Vault",
    category: "security",
    route: "/stealth-vault",
    description: "PBKDF2 + AES-256-GCM client-side encrypted vault with biometric (WebAuthn) unlock."
  },
  {
    name: "Cyber Command Center",
    category: "security",
    route: "/cyber-command",
    description: "Security modules including URL scanning and vulnerability intelligence feeds."
  },
  {
    name: "Knowledge Graph",
    category: "research",
    route: "/knowledge-graph",
    description: "Force-directed graph over your captured entities and research notes."
  },
  {
    name: "Local Models",
    category: "privacy",
    route: "/personal-llm",
    description: "Ollama and in-browser models so normal chat stays on your device."
  },
  {
    name: "Marketplace",
    category: "ecosystem",
    route: "/marketplace",
    description: "Installable specialist agents that run inside chat, with an 80% revenue share for authors."
  },
  {
    name: "Desktop App",
    category: "platform",
    route: "/download",
    description: "Cross-platform desktop build (Windows, macOS, Linux) with bundled offline runtime."
  }
];
var FAQS = [
  {
    question: "Do I need an account to try ShadowTalk?",
    answer: "No. You can start chatting from the /chatbot workspace without signing up; an account keeps your history and unlocks higher limits."
  },
  {
    question: "Is my data used for training?",
    answer: "No. ShadowTalk does not train on your conversations. Vault content is encrypted client-side, and normal chat can run on an on-device model."
  },
  {
    question: "What does ShadowTalk cost?",
    answer: "There is a free tier with no credit card. Paid plans are Pro $5/month, Premium $15/month and Elite $20/month."
  },
  {
    question: "Can I run it offline?",
    answer: "Yes. The desktop app bundles a local runtime (Ollama) and the browser app can download an in-browser model, so normal chat works without the cloud."
  },
  {
    question: "Which platforms are supported?",
    answer: "Web (PWA), Windows, macOS, Linux desktop builds, plus mobile via the installable PWA."
  }
];

// src/lib/mcp/tools/answer-faq.ts
var answer_faq_default = defineTool({
  name: "answer_faq",
  title: "Answer FAQ",
  description: "Search ShadowTalk AI's published FAQ (pricing, accounts, privacy, offline use, supported platforms) and return matching answers.",
  inputSchema: {
    question: z.string().optional().describe("The question to look up. Omit to return every FAQ entry.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ question }) => {
    const q = question?.trim().toLowerCase();
    const words = q ? q.split(/\W+/).filter((w) => w.length > 3) : [];
    const scored = FAQS.map((faq) => {
      const haystack = `${faq.question} ${faq.answer}`.toLowerCase();
      const score = words.filter((w) => haystack.includes(w)).length;
      return { faq, score };
    });
    const hits = words.length ? scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score).map((s) => s.faq) : FAQS;
    const results = hits.length > 0 ? hits : FAQS;
    const text = results.map((faq) => `**${faq.question}**
${faq.answer}`).join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { faqs: results, matched: hits.length > 0 && words.length > 0 }
    };
  }
});

// src/lib/mcp/tools/get-changelog.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";

// src/content/productChangelog.ts
var PRODUCT_CHANGELOG = [
  {
    version: "2.6.0",
    title: "Workspace-first experience",
    summary: "Open ShadowTalk straight into chat \u2014 faster entry, persistent sessions, cleaner composer.",
    publishedAt: "2026-06-01",
    tags: ["UX", "Auth", "Chat"],
    changes: [
      { type: "feature", text: "Site root (/) now opens the /chatbot workspace; marketing lives at /home." },
      { type: "feature", text: "Persistent sessions \u2014 return visits stay signed in; optional anonymous auto sign-in (Gemini-style)." },
      { type: "improvement", text: "Removed boot splash and \u201CWarming up\u2026\u201D screen on the chatbot path." },
      { type: "improvement", text: "Chat composer: send button aligned inside the pill; Turbo hardware badge removed from UI." },
      { type: "improvement", text: "Dedicated /pricing page with animated plan comparison." },
      { type: "improvement", text: "Marketing landing uses neural dock navigation (Pricing, Install, Login)." },
      { type: "bugfix", text: "Fixed coupon banner runtime error and header overlap on home." }
    ]
  },
  {
    version: "2.5.0",
    title: "App Builder & runnable Marketplace",
    summary: "Generate full web/mobile projects in the IDE; install agents that actually run in chat.",
    publishedAt: "2026-05-30",
    tags: ["IDE", "Marketplace"],
    changes: [
      { type: "feature", text: "App Builder \u2014 \u201Cbuild me an app\u201D creates multi-file projects and opens /ide with live preview." },
      { type: "feature", text: "Marketplace agents inject real system prompts, starters, and IDE scripts from /chatbot?agent=." },
      { type: "improvement", text: "Personal IDE: multi-file explorer, mobile viewport, templates, AI assist actions." }
    ]
  },
  {
    version: "2.4.0",
    title: "Hardware-aware speed paths",
    summary: "Automatic local WebGPU/WASM vs cloud routing on capable devices.",
    publishedAt: "2026-05-28",
    tags: ["Performance", "Offline"],
    changes: [
      { type: "feature", text: "Hardware intelligence scores CPU/GPU and caches profile for routing decisions." },
      { type: "feature", text: "Hybrid router sends simple messages to on-device models when ready." },
      { type: "improvement", text: "WebGPU prewarm runs in background without blocking chat input." },
      { type: "improvement", text: "Startup performance \u2014 deferred chrome, shared platform metrics, lazy landing sections." }
    ]
  },
  {
    version: "2.3.0",
    title: "BYOK & agentic tools",
    summary: "Bring your own API keys; Mission Control and expanded chat tooling.",
    publishedAt: "2026-05-20",
    tags: ["BYOK", "Agents"],
    changes: [
      { type: "feature", text: "BYOK for Gemini and Kimi \u2014 keys in Profile/Settings." },
      { type: "feature", text: "Mission Control (/missioncontrol) for multi-step autonomous workflows." },
      { type: "feature", text: "Command palette (\u2318K) for quick navigation and tool launch." },
      { type: "improvement", text: "Tool orchestration with human-in-the-loop confirmations on sensitive actions." }
    ]
  },
  {
    version: "2.2.0",
    title: "Foundation release",
    summary: "Desktop app, trust metrics, brand refresh, and agentic chat loop.",
    publishedAt: "2026-05-10",
    tags: ["Desktop", "Trust"],
    changes: [
      { type: "feature", text: "Electron desktop builds with native file picker and notifications." },
      { type: "feature", text: "Cyber Command Center \u2014 security copilot, scans, and ops modules." },
      { type: "improvement", text: "Honest product claims and live community metrics on landing." },
      { type: "security", text: "Security hardening migrations and stealth network guard options." }
    ]
  }
];

// src/lib/mcp/tools/get-changelog.ts
var get_changelog_default = defineTool2({
  name: "get_changelog",
  title: "Get changelog",
  description: "Return recent ShadowTalk AI release notes: version, title, summary and the individual changes.",
  inputSchema: {
    limit: z2.number().int().optional().describe("How many recent releases to return (1-20, default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ limit }) => {
    const count = Math.min(Math.max(Math.trunc(limit ?? 5), 1), 20);
    const entries = PRODUCT_CHANGELOG.slice(0, count);
    const text = entries.map((entry) => {
      const changes = entry.changes.map((change) => `  - [${change.type}] ${change.text}`).join("\n");
      return `## ${entry.version} \u2014 ${entry.title} (${entry.publishedAt})
${entry.summary}
${changes}`;
    }).join("\n\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { releases: entries }
    };
  }
});

// src/lib/mcp/tools/get-product-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_product_overview_default = defineTool3({
  name: "get_product_overview",
  title: "Get product overview",
  description: "Return an overview of ShadowTalk AI: what it is, who built it, the free tier, privacy posture and pricing plans.",
  inputSchema: {
    includePricing: z3.boolean().optional().describe("Include the full pricing plan breakdown. Defaults to true.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ includePricing = true }) => {
    const lines = [
      `# ${PRODUCT.name}`,
      PRODUCT.tagline,
      "",
      `Website: ${PRODUCT.website}`,
      `Founder: ${PRODUCT.founder}`,
      `Free tier: ${PRODUCT.freeTier}`,
      `Privacy: ${PRODUCT.privacy}`
    ];
    if (includePricing) {
      lines.push("", "## Plans");
      for (const plan of PLANS) {
        lines.push(`- **${plan.name}** (${plan.price}): ${plan.highlights.join(", ")}`);
      }
    }
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: {
        product: PRODUCT,
        plans: includePricing ? PLANS : void 0
      }
    };
  }
});

// src/lib/mcp/tools/list-features.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_features_default = defineTool4({
  name: "list_features",
  title: "List features",
  description: "List ShadowTalk AI features with their category, in-app route and a short description. Optionally filter by keyword or category.",
  inputSchema: {
    query: z4.string().optional().describe("Free-text keyword to filter features by name or description."),
    category: z4.string().optional().describe("Filter by category, e.g. chat, research, security, code, privacy, platform.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category }) => {
    const q = query?.trim().toLowerCase();
    const cat = category?.trim().toLowerCase();
    const matches = FEATURES.filter((feature) => {
      const inCategory = !cat || feature.category.toLowerCase() === cat;
      const inQuery = !q || feature.name.toLowerCase().includes(q) || feature.description.toLowerCase().includes(q);
      return inCategory && inQuery;
    });
    if (matches.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: `No features matched. Available categories: ${[
              ...new Set(FEATURES.map((f) => f.category))
            ].join(", ")}`
          }
        ],
        structuredContent: { features: [] }
      };
    }
    const text = matches.map(
      (f) => `- **${f.name}** (${f.category}) \u2014 ${f.description}
  ${PRODUCT.website}${f.route}`
    ).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { features: matches }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shadowtalk-ai",
  title: "ShadowTalk-AI",
  version: "0.1.0",
  instructions: "Public tools that expose ShadowTalk AI's published product information. Use `get_product_overview` for what the product is and how it is priced, `list_features` to explore features and their in-app routes, `get_changelog` for recent releases, and `answer_faq` for common questions. These tools return public marketing/product data only \u2014 no user accounts or private data.",
  tools: [get_product_overview_default, list_features_default, get_changelog_default, answer_faq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
