-- Self-improving agent memory table
-- Stores learned user memories as preference | skill | context
-- Timestamps default to now()

create table if not exists public.user_memories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('preference','skill','context')),
  key text not null,
  value jsonb not null,
  confidence numeric not null default 0.7,
  source text not null default 'reflection',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_memories enable row level security;

create policy "Users can view their own memories"
  on public.user_memories for select
  using (auth.uid() = user_id);

create policy "Users can insert their own memories"
  on public.user_memories for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own memories"
  on public.user_memories for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own memories"
  on public.user_memories for delete
  using (auth.uid() = user_id);

create index if not exists user_memories_user_id_idx
  on public.user_memories (user_id);

create index if not exists user_memories_category_idx
  on public.user_memories (category);
